#!/bin/sh
#!/bin/bash
# simple Bash Menu Script by jackluke

printf "OpenCore APFS 4 bootloader for BigSur unsupported Mac by jackluke"
echo "\n\nWelcome to the OpenCore APFS bootloader for BigSur unsupported Mac\n\nthis fix showing an useful menu, allows to detect any HFS, APFS, APFS ramdisk as bootable and unhidden volumes (also the Bootcamp partition)\n\nit allows also to detect macOS Install Data (that is the APFS OTA update installer) for non-APFS firmware machines as selectable bootable volume\nand to boot with telemetry fixed for Core2Duo and Legacy USB through CMD+S and exit"
echo "\nSetting nvram parameter to enforce compatibility check"
nvram boot-args="-no_compat_check"
echo "\nInstalling the bootloader to its boot path"
mkdir /Volumes/EFI
mount -t msdos /dev/disk0s1 /Volumes/EFI
unzip -qo -P jackluke /Applications/OpenCoreAPFSloader4.app/Contents/Resources/OpenCore -d /Volumes/EFI/
bless --folder /Volumes/EFI/EFI/Boot --label "OpenCoreAPFSloader4"
echo "\nDone"
echo "\nNow OpenCore bootloader is installed, to select at the next reboot hold alt-option key to show it on apple startup manager"
