#!/bin/sh
#!/bin/bash
# simple Bash Menu Script by jackluke

printf "BigSurFixes beta by jackluke"

printf "\n\n\n"

echo "Welcome to the BigSurFixes beta"
/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal /Applications/BigSurFixesBootfix.command
echo "Launching done, fixes applied, click Quit button and reboot with CMD+S to check if mount -uw / worked"