#!/bin/sh
#!/bin/bash
# simple Bash Menu Script by jackluke

printf "Uninstall OpenCore APFS 4 bootloader for BigSur unsupported Mac by jackluke"
echo "\n\nWelcome to the OpenCore APFS bootloader for BigSur unsupported Mac\n\nthis is the uninstaller"
echo "\nSetting nvram parameter to enforce compatibility check"
nvram boot-args="-no_compat_check"
echo "\nInstalling the bootloader to its boot path"
mkdir /Volumes/EFI
mount -t msdos /dev/disk0s1 /Volumes/EFI
rm /Volumes/EFI/EFI/BOOT/BOOTX64.efi
rm -r /Volumes/EFI/EFI/OC/
echo "\nDone"
echo "\nNow OpenCore bootloader is uninstalled, to select at the next reboot hold alt-option key to show it on apple startup manager"
